name: Android CI

on:
  push:
    branches: [ lyrix ]
    tags:
      - v*.*

  pull_request:
    branches: [ lyrix ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: |
        cd project
        chmod +x gradlew
    - name: Build with Gradle
      run: |
        cd project
        ./gradlew build

    - name: Create release and upload artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd project
        wget https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
        chmod +x pyuploadtool-x86_64.AppImage
        ./pyuploadtool-x86_64.AppImage app/build/outputs/apk/debug/app-debug.apk
